# Generated by Django 4.1.5 on 2023-01-14 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movieworld',
            name='img',
            field=models.ImageField(default='nsns', upload_to='pic'),
            preserve_default=False,
        ),
    ]
